### ISSUE TITLE
Included guava version 18 conflicts with selenium-java 3.12.0

### ISSUE THREAD

**Issue by dougnoel** [thoqbk/traprange#12]
When including the traprange jar in a project with selenium-java 3.12.0 in maven, the Guava version 18 conflicts. Attempting to instantiate a ChromeDriver object results in the following error:

java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:124)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:33)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:139)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:335)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)

Solution is to use a more recent version of Guava.

**Comment by thoqbk** [comment]
@dougnoel I checked, your merge request removed some resource files in `_Docs/ result`. I must temp rollback it. Can you help to send another merge request?

**Comment by dougnoel** [comment]
Yes

**Comment by dougnoel** [comment]
I looked and I did that because I thought _Docs/result was being generated
by the build process and so you don't need to store them. Is this not
correct?

**Comment by thoqbk** [comment]
@dougnoel they're for README.md, and `traprange.lastest.jar` is for `test-command-line.sh`

**Comment by dougnoel** [comment]
Ah ok. I will revert the changes. I will try to get that done today.
